# Generated by Django 3.1.1 on 2022-08-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
